// src/app/constants/permission.ts

export const PERMISSIONS = {
    // Employee
    EMPLOYEE_CREATE: 'EMPLOYEE_CREATE',
    EMPLOYEE_VIEW: 'EMPLOYEE_READ',      // key is VIEW, value matches backend _READ
    EMPLOYEE_UPDATE: 'EMPLOYEE_UPDATE',
    EMPLOYEE_DELETE: 'EMPLOYEE_DELETE',
    EMPLOYEE_APPROVE: 'EMPLOYEE_APPROVE',
    EMPLOYEE_REJECT: 'EMPLOYEE_REJECT',

    // Role
    ROLE_CREATE: 'ROLE_CREATE',
    ROLE_VIEW: 'ROLE_READ',              // key is VIEW, value matches backend _READ
    ROLE_UPDATE: 'ROLE_UPDATE',
    ROLE_DELETE: 'ROLE_DELETE',

    // Patient
    PATIENT_CREATE: 'PATIENT_CREATE',
    PATIENT_VIEW: 'PATIENT_READ',   // key is VIEW, value matches backend _READ
    PATIENT_UPDATE: 'PATIENT_UPDATE',
    PATIENT_DELETE: 'PATIENT_DELETE',
    PATIENT_PROFILE_READ: 'PATIENT_PROFILE_READ',
    PATIENT_PROFILE_UPDATE: 'PATIENT_PROFILE_UPDATE',

    // Appointment
    APPOINTMENT_CREATE: 'APPOINTMENT_CREATE',
    APPOINTMENT_VIEW: 'APPOINTMENT_READ',  // key is VIEW, value matches backend _READ
    APPOINTMENT_UPDATE: 'APPOINTMENT_UPDATE',
    APPOINTMENT_DELETE: 'APPOINTMENT_DELETE',
    APPOINTMENT_APPROVE: 'APPOINTMENT_APPROVE',
    APPOINTMENT_REJECT: 'APPOINTMENT_REJECT',
    APPOINTMENT_CANCEL: 'APPOINTMENT_CANCEL',

    // Health Records
    HEALTH_RECORD_CREATE: 'HEALTH_RECORD_CREATE',
    HEALTH_RECORD_READ: 'HEALTH_RECORD_READ',
    HEALTH_RECORD_UPDATE: 'HEALTH_RECORD_UPDATE',
    HEALTH_RECORD_DELETE: 'HEALTH_RECORD_DELETE',

    // Roles
    NODE_CREATE: 'NODE_CREATE',
    NODE_VIEW: 'NODE_READ',              // key is VIEW, value matches backend _READ
    NODE_UPDATE: 'NODE_UPDATE',
    NODE_DELETE: 'NODE_DELETE',

    // Branch
    BRANCH_CREATE: 'BRANCH_CREATE',
    BRANCH_READ: 'BRANCH_READ',
    BRANCH_UPDATE: 'BRANCH_UPDATE',
    BRANCH_DELETE: 'BRANCH_DELETE',

    // Other
    AUDIT_READ: 'AUDIT_READ',
    DASHBOARD_READ: 'DASHBOARD_READ',

} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];