sonar.projectKey=SPRINT2
sonar.projectName=SPRINT2
Node App sonar.projectVersion=1.0
sonar.sources=HMS-BACKEND-A/src,HMSFE/src
sonar.language=js
sonar.sourceEncoding=UTF-8
# Exclusions
sonar.exclusions=node_modules/**,test/**
# Test coverage
# sonar.tests=test sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Server & auth
sonar.host.url=http://localhost:9000
sonar.login=sqp_1ac46128f811be27c29f93923e5e4329eb6acc01