sonar.projectKey=hms-backend
sonar.projectName=hms-backend 
sonar.projectVersion=1.0 
sonar.sources=src 
sonar.language=js 
sonar.sourceEncoding=UTF-8 
# Exclusions 
sonar.exclusions=node_modules/**,test/** 


# Test coverage 
# sonar.tests=test 
sonar.javascript.lcov.reportPaths=coverage/lcov.info 
# Server & auth 
sonar.host.url=http://localhost:9000 
sonar.Login=sqp_a3d4546f153c38ff6b12def476b2317d1cacaa74
 