sonar.projectKey=hms-backend 
sonar.projectName=hms-backend
sonar.projectVersion=1.0 
sonar.sources=src 
sonar.language=js 
sonar.sourceEncoding=UTF-8 
# Exclusions 
sonar.exclusions=node_modules/** 
sonar.coverage.exclusions=**
# Test coverage 
#sonar.tests=test 
# sonar.javascript.lcov.reportPaths=coverage/lcov.info 
# Server & auth 
sonar.host.url=http://localhost:9000 
sonar.login=sqp_a789c2dd9dbb4f1f6ea7ea62ae7cef2a4e1f20f6
sonar.java.jdkHome=C:\Program Files\OpenLogic\jre-22.0.2.9-hotspot