sonar.projectKey=MYAPP
sonar.projectName=MYAPP
Node App sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=node_modules/**,test/**
# Test coverage
# sonar.tests=test sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Server & auth
sonar.host.url=http://localhost:9000
sonar.token=sqp_9bc4861049873e52cafbd73d089b26c5a1c5dd8a

sonar.coverage.exclusions = **




