sonar.projectKey=hms-react
sonar.projectName=hms-react
Node App sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=node_modules/**,test/**
# Test coverage
# sonar.tests=test sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Server & auth
sonar.host.url=http://localhost:9000
sonar.token= sqp_e6b750448a0a9a1cc094081a439949a6749119c9

sonar.coverage.exclusions = **





