const PERMISSIONS = {
    // --- Employee Permissions ---
    EMPLOYEE_CREATE: "EMPLOYEE_CREATE",
    EMPLOYEE_VIEW: "EMPLOYEE_READ",   // Changed from EMPLOYEE_VIEW to match DB
    EMPLOYEE_UPDATE: "EMPLOYEE_UPDATE",
    EMPLOYEE_DELETE: "EMPLOYEE_DELETE",
    EMPLOYEE_APPROVE: "EMPLOYEE_APPROVE",
    EMPLOYEE_REJECT: "EMPLOYEE_REJECT",

    // --- Role Permissions ---
    ROLE_CREATE: "ROLE_CREATE",
    ROLE_VIEW: "ROLE_READ",           // Changed from ROLE_VIEW to match DB
    ROLE_UPDATE: "ROLE_UPDATE",
    ROLE_DELETE: "ROLE_DELETE",

    // --- Patient Permissions ---
    PATIENT_CREATE: "PATIENT_CREATE",
    PATIENT_VIEW: "PATIENT_READ",     // Changed from PATIENT_VIEW to match DB
    PATIENT_UPDATE: "PATIENT_UPDATE",
    PATIENT_DELETE: "PATIENT_DELETE",
    PATIENT_PROFILE_READ: "PATIENT_PROFILE_READ",
    PATIENT_PROFILE_UPDATE: "PATIENT_PROFILE_UPDATE",

    // --- Appointment Permissions ---
    APPOINTMENT_CREATE: "APPOINTMENT_CREATE",
    APPOINTMENT_VIEW: "APPOINTMENT_READ", // Changed from APPOINTMENT_VIEW to match DB
    APPOINTMENT_UPDATE: "APPOINTMENT_UPDATE",
    APPOINTMENT_DELETE: "APPOINTMENT_DELETE",
    APPOINTMENT_APPROVE: "APPOINTMENT_APPROVE",
    APPOINTMENT_REJECT: "APPOINTMENT_REJECT",
    APPOINTMENT_CANCEL: "APPOINTMENT_CANCEL",

    // --- System / Dashboard Permissions ---
    DASHBOARD_VIEW: "DASHBOARD_READ",
    AUDIT_VIEW: "AUDIT_READ",

    // --- Node Permissions ---
    NODE_VIEW: "NODE_READ",
    NODE_CREATE: "NODE_CREATE",
    NODE_UPDATE: "NODE_UPDATE",
    NODE_DELETE: "NODE_DELETE",

    // --- Branch Permissions ---
    BRANCH_VIEW: "BRANCH_READ",

    // --- Health Record Permissions ---
    HEALTH_RECORD_CREATE: "HEALTH_RECORD_CREATE",
    HEALTH_RECORD_READ: "HEALTH_RECORD_READ",
    HEALTH_RECORD_UPDATE: "HEALTH_RECORD_UPDATE",
    HEALTH_RECORD_DELETE: "HEALTH_RECORD_DELETE"
};

module.exports = { PERMISSIONS };