const PERMISSIONS = {
    EMPLOYEE_CREATE: "EMPLOYEE_CREATE",
    EMPLOYEE_VIEW: "EMPLOYEE_VIEW",
    EMPLOYEE_UPDATE: "EMPLOYEE_UPDATE",
    EMPLOYEE_DELETE: "EMPLOYEE_DELETE",

    ROLE_CREATE: "ROLE_CREATE",
    ROLE_VIEW: "ROLE_VIEW",
    ROLE_UPDATE: "ROLE_UPDATE",
    ROLE_DELETE: "ROLE_DELETE",

    PATIENT_CREATE: "PATIENT_CREATE",
    PATIENT_VIEW: "PATIENT_VIEW",
    PATIENT_UPDATE: "PATIENT_UPDATE",
    PATIENT_DELETE: "PATIENT_DELETE",

    APPOINTMENT_CREATE: "APPOINTMENT_CREATE",
    APPOINTMENT_VIEW: "APPOINTMENT_VIEW",
    APPOINTMENT_UPDATE: "APPOINTMENT_UPDATE",
    APPOINTMENT_DELETE: "APPOINTMENT_DELETE"
};

module.exports = { PERMISSIONS };